name: Deploy to Github Pages

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Config git with email and name
        run: git config user.name danielm2048 && git config user.email danielmimoun98@gmail.com

      - name: Create gh-pages branch
        run: git checkout --orphan gh-pages

      - name: Build Svelte app
        run: npm run build

      - name: Add build files to branch
        run: git --work-tree public add --all

      - name: Commit build files to branch
        run: git --work-tree public commit -m 'Deploy'

      - name: Push build files to branch
        run: git push origin HEAD:gh-pages --force

      - name: Go back to main branch
        run: git checkout -f main

      - name: Delete gh-pages branch
        run: git branch -D gh-pages
